### ISSUE TITLE
find: `out': No such file or directory

### ISSUE THREAD

**Issue by Donaldhan** [slashdotdash/jekyll-lunr-js-search#125]
when i gem  gem install jekyll-lunr-js-search, i get the error as follow:

```
current directory: D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/ext/libv8
D:/Ruby23-x64/Ruby23-x64/bin/ruby.exe -r ./siteconf20171107-7496-1a56bac.rb extconf.rb
creating Makefile
find: `out': No such file or directory
GYP_GENERATORS=make \
        build/gyp/gyp --generator-output="out" build/all.gyp \
                      -Ibuild/standalone.gypi --depth=. \
                      -Dv8_target_arch=ia32 \
                      -S.ia32  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3
GYP_GENERATORS=make \
        build/gyp/gyp --generator-output="out" build/all.gyp \
                      -Ibuild/standalone.gypi --depth=. \
                      -Dv8_target_arch=x64 \
                      -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3
Patching out/build/All.target.ia32.mk...
Patching out/build/All.target.x64.mk...
Patching out/Makefile.ia32...
Patching out/Makefile.x64...
Patching out/preparser/preparser.target.ia32.mk...
Patching out/preparser/preparser.target.x64.mk...
Patching out/samples/lineprocessor.target.ia32.mk...
Patching out/samples/lineprocessor.target.x64.mk...
Patching out/samples/process.target.ia32.mk...
Patching out/samples/process.target.x64.mk...
Patching out/samples/shell.target.ia32.mk...
Patching out/samples/shell.target.x64.mk...
Patching out/src/d8.target.ia32.mk...
Patching out/src/d8.target.x64.mk...
Patching out/src/d8_js2c.host.x64.mk...
Patching out/src/d8_js2c.target.ia32.mk...
Patching out/tools/gyp/js2c.host.x64.mk...
Patching out/tools/gyp/js2c.target.ia32.mk...
Patching out/tools/gyp/mksnapshot.host.x64.mk...
Patching out/tools/gyp/mksnapshot.target.ia32.mk...
Patching out/tools/gyp/postmortem-metadata.target.ia32.mk...
Patching out/tools/gyp/postmortem-metadata.target.x64.mk...
Patching out/tools/gyp/preparser_lib.target.ia32.mk...
Patching out/tools/gyp/preparser_lib.target.x64.mk...
Patching out/tools/gyp/v8.host.x64.mk...
Patching out/tools/gyp/v8.target.ia32.mk...
Patching out/tools/gyp/v8.target.x64.mk...
Patching out/tools/gyp/v8_base.host.x64.mk...
Patching out/tools/gyp/v8_base.target.ia32.mk...
Patching out/tools/gyp/v8_base.target.x64.mk...
Patching out/tools/gyp/v8_nosnapshot.host.x64.mk...
Patching out/tools/gyp/v8_nosnapshot.target.ia32.mk...
Patching out/tools/gyp/v8_nosnapshot.target.x64.mk...
Patching out/tools/gyp/v8_shell.host.x64.mk...
Patching out/tools/gyp/v8_shell.target.ia32.mk...
Patching out/tools/gyp/v8_snapshot.host.x64.mk...
Patching out/tools/gyp/v8_snapshot.target.ia32.mk...
Patching out/tools/gyp/v8_snapshot.target.x64.mk...
make[1]: Entering directory `/d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out'
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/diy-fp.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/dtoa.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fast-dtoa.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fixed-dtoa.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/once.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparse-data.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser-api.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/scanner.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/strtod.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/token.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/unicode.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/utils.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/win32-math.o
  AR(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/tools/gyp/libpreparser_lib.a
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser/preparser/preparser-process.o
  LINK(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/preparser
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/allocation.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/api.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/assembler.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/ast.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/atomicops_internals_x86_gcc.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/bignum-dtoa.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/bignum.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/bootstrapper.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/builtins.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/cached-powers.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/checks.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/circular-queue.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/code-stubs.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/code-stubs-hydrogen.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/codegen.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/compilation-cache.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/compiler.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/contexts.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/conversions.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/counters.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/cpu-profiler.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/data-flow.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/date.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/dateparser.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/debug-agent.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/debug.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/deoptimizer.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/disassembler.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/diy-fp.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/dtoa.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/elements-kind.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/elements.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/execution.o
  CXX(target) /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/extensions/externalize-string-extension.o
../src/extensions/externalize-string-extension.cc:141:3: fatal error: opening dependency file /d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/.deps//d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/extensions/externalize-string-extension.o.d.raw: No such file or directory
compilation terminated.
make[1]: *** [/d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/v8_base/src/extensions/externalize-string-extension.o] Error 1
make[1]: Leaving directory `/d/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out'
make: *** [x64.release] Error 2
D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive 'D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
        from D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:35:in `each'
        from D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:35:in `verify_installation!'
        from D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:26:in `install!'
        from extconf.rb:7:in `<main>'
Applying D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/patches/disable-building-tests.patch
Applying D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/patches/disable-werror-on-osx.patch
Applying D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/patches/disable-xcode-debugging.patch
Applying D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/patches/do-not-imply-vfp3-and-armv7.patch
Applying D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/patches/do-not-use-MAP_NORESERVE-on-freebsd.patch
Applying D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/patches/do-not-use-vfp2.patch
Applying D:/Ruby23-x64/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/patches/fPIC-for-static.patch
Compiling v8 for x64
Using python 2.7.14
Using compiler: g++ (GCC version 4.7.2)
Beginning compilation. This will take some time.
Building v8 with env CXX=g++ LINK=g++ make x64.release

extconf failed, exit code 1

```
from the output, i cann't find answer....

**Comment by Donaldhan** [comment]
it is the output dir not exists, seems un possible...

**Comment by Donaldhan** [comment]
the fulltext search jekyll-tipue-search base liquid is easy[jekyll-tipue-search]( https://github.com/Donaldhan/jekyll-tipue-search)
