### ISSUE TITLE
Can not install the plugin as a gem

### ISSUE THREAD

**Issue by iloveip** [slashdotdash/jekyll-lunr-js-search#56]
Hi there, 
I'm having some trouble installing the plugin as a gem.

I've done the following steps: 1a, 2a, 4, 5, 6, 7. But when I build the site I get the following error:

````
Malahovas-MacBook-Pro:iloveip Svetlana$ rake
Configuration file: /Users/Svetlana/Desktop/iloveip/_config.yml
/Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-lunr-js-search (LoadError)
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `call'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `each'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `execute'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/program.rb:35:in `go'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary.rb:22:in `program'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/jekyll:23:in `load'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/jekyll:23:in `<main>'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `<main>'
Malahovas-MacBook-Pro:iloveip Svetlana$
````

How can I fix it?

**Comment by iloveip** [comment]
I also tried to do the last part. I already have Bundler and ran `bundle install`. Then I installed Bower. But when I run `rake build`, I get the following error:

````
Malahovas-MacBook-Pro:iloveip Svetlana$ rake build --trace
rake aborted!
Don't know how to build task 'build'
/Users/Svetlana/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/rake/task_manager.rb:49:in `[]'
/Users/Svetlana/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/rake/application.rb:142:in `invoke_task'
/Users/Svetlana/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/Svetlana/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/rake/application.rb:101:in `each'
/Users/Svetlana/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/rake/application.rb:101:in `block in top_level'
/Users/Svetlana/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/rake/application.rb:110:in `run_with_threads'
/Users/Svetlana/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/rake/application.rb:95:in `top_level'
/Users/Svetlana/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/rake/application.rb:73:in `block in run'
/Users/Svetlana/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/Users/Svetlana/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/rake/application.rb:70:in `run'
/Users/Svetlana/.rvm/rubies/ruby-2.0.0-p451/bin/rake:37:in `<main>'
Malahovas-MacBook-Pro:iloveip Svetlana$ 

````

**Comment by slashdotdash** [comment]
@iloveip From the first error message it looks as though Jekyll cannot load the gem. Could you try installing with `sudo`.

     sudo gem install jekyll-lunr-js-search

You shouldn't need to run bundle or rake as those are for building the plugin from source (e.g. if you wanted to make any changes to the plugin).

**Comment by iloveip** [comment]
@slashdotdash I've installed it with `sudo` and still get an error:

````
Malahovas-MacBook-Pro:iloveip Svetlana$ rake
Configuration file: /Users/Svetlana/Desktop/iloveip/_config.yml
/Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-lunr-js-search (LoadError)
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `call'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `each'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `execute'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/program.rb:35:in `go'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary.rb:22:in `program'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/jekyll:23:in `load'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/jekyll:23:in `<main>'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `<main>'
Malahovas-MacBook-Pro:iloveip Svetlana$ 
````

Also when the gem was being installed I had the following warnings:

````
Malahovas-MacBook-Pro:iloveip Svetlana$ sudo gem install jekyll-lunr-js-search

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
Fetching: mini_portile-0.6.2.gem (100%)
Successfully installed mini_portile-0.6.2
Fetching: nokogiri-1.6.5.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.5
Fetching: json-1.8.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-1.8.2
Fetching: ref-1.0.5.gem (100%)
Successfully installed ref-1.0.5
Fetching: libv8-3.16.14.7.gem (100%)
Building native extensions.  This could take a while...
Successfully installed libv8-3.16.14.7
Fetching: therubyracer-0.12.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed therubyracer-0.12.1
Fetching: jekyll-lunr-js-search-0.2.1.gem (100%)
Successfully installed jekyll-lunr-js-search-0.2.1
Parsing documentation for jekyll-lunr-js-search-0.2.1
Installing ri documentation for jekyll-lunr-js-search-0.2.1
Parsing documentation for json-1.8.2
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ../../extensions/x86_64-darwin-12/2.0.0-static/json-1.8.2/json/ext/generator.bundle, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ../../extensions/x86_64-darwin-12/2.0.0-static/json-1.8.2/json/ext/parser.bundle, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/json/ext/generator.bundle, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/json/ext/parser.bundle, skipping
Installing ri documentation for json-1.8.2
Parsing documentation for libv8-3.16.14.7
Installing ri documentation for libv8-3.16.14.7
Parsing documentation for mini_portile-0.6.2
Installing ri documentation for mini_portile-0.6.2
Parsing documentation for nokogiri-1.6.5
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ../../extensions/x86_64-darwin-12/2.0.0-static/nokogiri-1.6.5/nokogiri/nokogiri.bundle, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/nokogiri/nokogiri.bundle, skipping
Installing ri documentation for nokogiri-1.6.5
Parsing documentation for ref-1.0.5
Installing ri documentation for ref-1.0.5
Parsing documentation for therubyracer-0.12.1
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ../../extensions/x86_64-darwin-12/2.0.0-static/therubyracer-0.12.1/v8/init.bundle, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/accessor.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/array.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/backref.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/constants.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/constraints.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/context.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/date.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/exception.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/external.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/function.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/gc.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/handles.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/heap.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/init.bundle, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/init.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/invocation.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/locker.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/message.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/object.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/primitive.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/rr.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/script.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/signature.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/stack.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/string.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/template.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/trycatch.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/v8.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for ext/v8/value.o, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/v8/init.bundle, skipping
Installing ri documentation for therubyracer-0.12.1
7 gems installed
````

**Comment by iloveip** [comment]
Hi there,

Any update on this issue?

**Comment by tomjohnson1492** [comment]
I got a similar error. I tried installing the pre-built plugin only and got similar errors. I [described the issues here on stackoverflow](http://stackoverflow.com/questions/28255836/why-am-i-getting-an-error-when-installing-lunr-js-search-on-jekyll). Any ideas on how to get around these errors?
